package com.kgdatasolutions.podcastbackend.dto.auth;

public enum Auth_Status {
    USER_CREATED_SUCCESSFULLY, USER_REGISTRATION_FAILED, USER_ALREADY_EXISTS, USER_DELETED_SUCCESSFULLY, USER_DELETION_FAILED,
    LOGIN_SUCCESS, LOGIN_FAILED, TOKEN_REFRESH_SUCCESSFULLY, TOKEN_REFRESH_FAILED, PASSWORD_CHANGED_SUCCESSFULLY, PASSWORD_UPDATE_FAILED,
    USER_NOT_FOUND, PASSWORD_RESET_SUCCESSFULLY, INSUFFICIENT_SECURITY_ANSWERS, ERROR_OCCURRED, ADMIN_ALREADY_EXISTS
}
