name: Deploy App to Azure App Service

on:
  push:
    branches:
      - deploy-to-azure-app-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: podcast-application
          path: ${{ github.workspace }}/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build

    env:
      MONGODB_CONNECTION_URI: ${{ vars.MONGODB_CONNECTION_URI }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ vars.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_STORAGE_CONTAINER_NAME: ${{ vars.AZURE_STORAGE_CONTAINER_NAME }}

    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: podcast-application

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: podcast-application-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
