name: Example Workflow

on:
  push:
    branches:
      - backend # Add the branch you want the action to run on
  pull_request:
    branches:
      - master  # Add the branch you want the action to run on

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, World!"
